declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_APP_FIREBASE_API_KEY: string
    NEXT_APP_FIREBASE_AUTH_DOMAIN: string
    NEXT_APP_FIREBASE_PROJECT_ID: string
    NEXT_APP_FIREBASE_STORAGE_BUCKET: string
    NEXT_APP_FIREBASE_MESSAGING_SENDER_ID: string
    NEXT_APP_FIREBASE_MESSAGING_APP_ID: string
    NEXT_APP_FIREBASE_MEASUREMENT_ID: string
  }
}
